// Code generated by mockery v2.20.2. DO NOT EDIT.

package client

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GlacierHTTPClient is an autogenerated mock type for the GlacierHTTPClient type
type GlacierHTTPClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, url
func (_m *GlacierHTTPClient) Get(ctx context.Context, url string) ([]byte, error) {
	ret := _m.Called(ctx, url)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGlacierHTTPClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewGlacierHTTPClient creates a new instance of GlacierHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGlacierHTTPClient(t mockConstructorTestingTNewGlacierHTTPClient) *GlacierHTTPClient {
	mock := &GlacierHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
